### ISSUE TITLE
Type Mismatch Error: Cannot convert value of type 'QuizView.ViewModel' to expected argument type 'Sura'

### ISSUE THREAD

**Issue by MohammadArsalan97** [takasurazeem/QuranMajeed#47]
I am encountering a type mismatch error in the app when attempting to pass a value of type 'QuizView.ViewModel' to a View that expects an argument of type 'Sura'. This error is preventing the app from compiling successfully.

<img width="1011" alt="Screenshot 2023-12-31 at 3 09 37 AM" src="https://github.com/takasurazeem/QuranMajeed/assets/53628432/fb13e1d3-dec4-4b16-84d8-69c6c9873acc">

**Comment by takasurazeem** [comment]
Please remove this line of code @MohammadArsalan97. Thanks for catching it.

**Comment by takasurazeem** [comment]
**git fetch origin
git checkout 47-type-mismatch-error-cannot-convert-value-of-type-quizviewviewmodel-to-expected-argument-type-sura**
